- package.json
> Use correct "main" module in package.json: "src/wampy.js"

- .crossbar/Dockerfile
- .travis.yml
- package-lock.json
* Removed Chrome addon (obsolete)
* Replaced Python and Pip via Docker in `travis.yml`
* Added script that waits for crossbar node to launch
* Added Dockerfile
pip install + sleep 5
docker run + wait for specific output from the container
> Travis: crossbar installation -> docker container

- README.md
- src/wampy.js
#102 
wampy does not accept URI's with loose validation
If uriValidation set to 'loose' wampy will be less strict about topic URI's
> added a uriValidation option with strict and loose as options

- .babelrc
- package-lock.json
- package.json
Improve code coverage report
Was before:
Became after:
> Fix code coverage report

- src/wampy.js
> Refactored working with ppt/e2ee payload: extracted to helpers methods

- .babelrc
- .github/workflows/build-and-test.yml
- README.md
- package-lock.json
- package.json
- src/constants.js
- src/wampy.js
- test/send-data.js
- test/wampy-common-test.js
Added Wamp cryptosign auth flow. Described in docs.
> Wamp cryptosign

- README.md
- src/constants.js
- src/errors.js
- src/wampy.js
- test/send-data.js
- test/wampy-common-test.js
Added Error classes for all errors that wampy can throw. Updated docs about errors handling.
Thrown errors are not formalized
All possible errors are thrown as custom Error instances
> Errors handling

- .eslintrc.json
- package-lock.json
- src/wampy.js
(Describe your changes in detail)
- Improve readability in methods "_log", "_preReqCheck" and "_validateURI";
- Change some unnecessary "let" declarations to "const";
- Improve "err" object names;
- Add two new useful .eslintrc.json rules;
- Fix some package-lock.json vulnerabilities with "npm audit fix";
(You can also link to an open issue here)
(if this is a feature change)
> Some refactoring in src/wampy.js

- src/utils.js
- test/wampy-utils-test.js
Refactor utils.js for better readability:
- Add helper function isWebSocketSchemeSpecified to explain the regex;
- Change unnecessary "let" to "const";
- Use string template literals instead of string concatenation;
> Refactor utils

- .eslintrc.json
- test/wampy-crossbar-test.js
- Use async/await paradigm instead of .then();
- Group duplicate code into const declarations;
- Change ESLint parsing version to "latest" so it doesn't complain about the use of the object spreading operator (...);
> Refactor wampy-crossbar-test.js

- test/wampy-serializer-handshake-test.js
- Group duplicate code into "consts";
- Import just "NoSerializerAvailableError" instead of importing all errors;
- Improve error variable naming for better readability;
> Refactor wampy-serializer-handshake-test.js

- test/fake-ws.js
- Group duplicate code into consts;
- Replace Switch with Object Literals;
- Simplify logic for better readability;
> Refactor fake-ws.js

- src/wampy.js
Refactor "unsubscribe" to reduce cognitive complexity
> Refactor "unsubscribe" to reduce cognitive complexity

- src/wampy.js
Refactor "cancel" to reduce cognitive complexity
> Refactor "cancel" to reduce cognitive complexity

- .eslintrc.json
- src/utils.js
- src/wampy.js
- test/fake-ws.js
- test/wampy-common-test.js
- test/wampy-utils-test.js
The [prefer-const ESLint rule](https://eslint.org/docs/latest/rules/prefer-const) detects variables that are not reassigned and suggests them to be declared as "const" instead;
> Add "prefer-const" ESLint rule and run lint:fix

- .github/pull_request_template.md
So I don't have to type it in everytime haha
> Add 'Refactoring' to the PR template

- src/wampy.js
Refactor 'connect' to reduce cognitive complexity
> Refactor 'connect' to reduce cognitive complexity

- src/wampy.js
Refactor 'subscribe' to reduce cognitive complexity
> Refactor 'subscribe' to reduce cognitive complexity

- test/fake-ws-set-protocol.js
- test/fake-ws.js
- test/wampy-common-test.js
This fixes a few eslint warnings. 
Also closes #208
> Fixed some eslint warnings related to const/let

- src/wampy.js
Rewrite 'call' using Object destructuring, allowing the "options" object to receive all advancedOptions properties, even the ones that are not defined, thus making the code shorter and more dynamic.
> Refactor 'call' to reduce cognitive complexity

- src/wampy.js
- Object destructuring can be done conditionally, which makes us able to get rid of some if/else logic
- Also it looks even cleaner
> Replace Object.assign with Object destructuring (...)

- src/wampy.js
- Before, '_wsOnMessage' had a huge Switch/Case which led to a lot of nested code and difficult to read logic.
- Now, each message type has its own internal function and '_wsOnMessage' just selects the correct message handler depending on its type.
> Refactor '_wsOnMessage' to use Object literals instead of Switch/Case

- src/wampy.js
Refactor 'register' to reduce cognitive complexity
> Refactor 'register' to reduce cognitive complexity

- src/wampy.js
Refactor 'unregister' to reduce cognitive complexity
> Refactor 'unregister' to reduce cognitive complexity

- src/wampy.js
Refactor '_onSubscribedMessage' and '_onUnsubscribedMessage' to reduce cognitive complexity
> Refactor '_onSubscribedMessage' and '_onUnsubscribedMessage'

- package.json
- The 'npx' command (available since npm version 5.2) makes the package.json scripts simpler and easier to read.
- Also, remove script duplicates by adding extra parameters to previous scripts instead.
> Rewrite package.json scripts to use npx

- src/wampy.js
Refactor '_packPPTPayload' to reduce cognitive complexity
> Refactor '_packPPTPayload' to reduce cognitive complexity

- src/wampy.js
Refactor '_onInvocationMessage' to reduce cognitive complexity
> Refactor '_onInvocationMessage' to reduce cognitive complexity

- src/wampy.js
Refactor _onPublishedMessage to reduce cognitive complexity
> Refactor _onPublishedMessage

- src/wampy.js
Change the "data" parameter to a destructured Array, so that it matches the WAMP spec better and is easier to understand
> Improve readability for _onRegister and _onUnregister

- src/wampy.js
Refactor '_onErrorMessage' to use object literals instead of switch/case
> Refactor '_onErrorMessage' to use object literals instead of switch/case

- src/wampy.js
Refactor '_onAbortMessage' to use array instead of data object
> Refactor '_onAbortMessage' to use array instead of data object

- src/wampy.js
Refactor '_onChallengeMessage' to use array instead of data object
> Refactor '_onChallengeMessage' to use array instead of data object

- src/wampy.js
Refactor '_onWelcomeMessage' to use array instead of data object
> Refactor '_onWelcomeMessage' to use array instead of data object

- src/wampy.js
Refactor '_onResultMessage' to use array instead of data object
> Refactor '_onResultMessage' to use array instead of data object

- src/wampy.js
Refactor '_onEventMessage' to use array instead of data object
> Refactor '_onEventMessage' to use array instead of data object

- src/wampy.js
Refactor 'publish' to reduce cognitive complexity
> Refactor 'publish' to reduce cognitive complexity

- src/wampy.js
Refactor '_wsOnOpen' to reduce cognitive complexity
> Refactor '_wsOnOpen' to reduce cognitive complexity

- karma.conf.cjs
- package-lock.json
- package.json
Remove unused 'puppeteer' devDependency
> Remove unused 'puppeteer' devDependency

- src/wampy.js
- test/send-data.js
- test/wampy-common-test.js
> fix: rejecting connection promise on ABORT message

- src/wampy.js
These three functions had similar structures but were using slightly different code.
Now, they have been unified so that their structures looks the same:
- Using "messageOptions" instead of "options";
- Using "{}" as a fallback instead of "null";
- Handling "payloadItems" in the message array itself;
> Improve consistency between call, publish and handleInvocationResult

- package-lock.json
- package.json
> Revert Mocha back to 9.2.2

- package-lock.json
- package.json
- src/wampy.js
- test/wampy-browser-wrappers-test.js
- Add wampy-browser-wrappers-test.js;
- Add dev dependencies 'jsdom' and 'jsdom-global' to simulate browser environment for tests;
- Add a script to test the browser wrappers exclusively;
> Add tests for browser.js and serializers4browser.js

- src/wampy.js
Move requestId validation to _wsOnMessage, removing duplicate code from multiple functions, improving test coverage and fixing 1 code climate suggestion
> Move requestId validation to _wsOnMessage increasing test coverage by +0.4%

- .github/workflows/build-and-test.yml
Update CI cfg to include Node.js v20
(You can also link to an open issue here)
(if this is a feature change)
> Update node versions in CI matrix

- README.md
- src/wampy.js
> Fix unhandled promise rejection (exceptions) during reconnection logic.

- .github/workflows/build-and-test.yml
(Describe your changes in detail)
(You can also link to an open issue here)
(if this is a feature change)
> Update CI actions versions

- eslint.config.js
- package-lock.json
- package.json
Added a `eslint-plugin-security` which is:
ESLint rules for Node Security. This project will help identify potential security hotspots.
> Add eslint-plugin-security

- package-lock.json
- package.json
Update chai to latest v4.
Can't figure out how to fix chai v5.... :(
> Update chai to latest v4

- test/send-data.js
- test/wampy-common-test.js
It seems I found the problem when `allows to connect to same WAMP server` test was failing (at least locally for me) and some times in CI.
> Fix failing tests in browser/karma env

- README.md
- cmd/wampy-helpers.js
- package-lock.json
- package.json
- src/auth/cryptosign/README.md
- src/auth/cryptosign/wampy-cryptosign.js
- test/wampy-cryptosign-test.js
In this PR wampy cryptosign plugin from a [standalone repo](https://github.com/KSDaemon/wampy-cryptosign) is merged into main codebase.
This closes #435
> Merge "wampy-cryptosign" plugin

- src/auth/cryptosign/wampy-cryptosign.js
This PR just adds a JS doc comments to wampy cryptosign plugin public API surface.
> Added js doc comments to the cryptosign plugin functions

- README.md
- cmd/wampy-helpers.js
- package.json
- src/auth/wampcra/README.md
- src/auth/wampcra/wampy-cra.js
- test/wampy-cra-test.js
This is a continuation of process of auth plugin consolidation inside main codebase. This one brings [wampy-cra plugin](https://github.com/KSDaemon/wampy-cra).
Closes #434
> Imported wampy wampCRA plugin
