src/wampy.js

Use protocol from `this._ws.protocol` only if it is defined

---

dist/wampy.js
src/wampy.js

The ^ operation in javascript means XOR and not 'raise to the power of'.
In busy situations this caused webapps to hang because all ID's below 55
were in use.

Limit generated ID's on some bigger number than 55

---

src/wampy.js

Fix for #100 
Subscriptions that are made with advancedOptions are not re-applied after a re-connect
The advancedOption is persisted with the subscription and can be re-applied on reconnect

persist advancedOptions for potential auto reconnect

---

src/wampy.js

Fixes #97 - In Node environment, `obj.constructor === Object` was returning `false`, perhaps due to some overload or monkey patch?
Based on jonschlinkert/is-plain-object.
#97  - In Node env, default settings were used, regardless of what options were passed into constructor

Fix _isPlainObject

---

Gruntfile.js
src/msgpacksrlzrbrowser.js
src/wampy.js

I needed IE support so I cannot use the most recent v6.x releases. When I tried to use the msgpack support in v5.0.1 in a browser context, MsgpackSerializer was undefined. After fixing that in the build process, enabling Msgpack threw an exception which I then fixed.
Msgpack support does not work in the browser for v5.0.1.
Msgpack support works.

Fix msgpack support.

---

README.md
src/wampy.js

The README file has confusing examples from 5.x syntax of subscribe().
This fixes that issue.

README has confusing old 5.x examples

---

src/wampy.js

For the [Nexus](https://github.com/gammazero/nexus) WAMP router to provide
publisher identification info to subscribers, it requires that 'publisher-identification' be true
in the subscriber.features in the right place in the JSON. I am not an author on Nexus.
[publisher-identification](https://wamp-proto.org/_static/gen/wamp_latest.html#publisher-identification)
My reading of the spec supports that it is truly needed in the features in the HELLO,
to enable passing of the sessionid in the 'details.publisher' field of pubsub messages.
[Feature Announcement of publisher_identification](https://wamp-proto.org/_static/gen/wamp_latest.html#feature-announcement-11)
I am thrilled to be using Wampy, thanks to all the great coders who worked on it!

add publisher_identification to subscriber.features as per spec

---

.vscode/extensions.json
CONTRIBUTING.md
Migrating.md
README.md

(Describe your changes in detail)
- Run a markdown file linter from the VSCode extension "Markdown All in One" to fix unwanted patterns in *.md files;
- Add VSCode extension recommendations to .vscode/extensions.json to enforce usage of markdown linter, ESLint, and EditorConfig for new contributors who open the project in VSCode;
- Improve grammar and add minor code improvements in README.md such as using arrow function syntax for functions instead of the "function" keyword and converting unnecessary "let" constants to "const";
(You can also link to an open issue here)
Docs do not conform to a common markdown linting pattern
(if this is a feature change)
Docs are now linted and formatted following https://github.com/DavidAnson/markdownlint/ and using the "Markdown All in One" VSCode …

docs: lint markdown files with "Markdown All in One" formatter

---

package.json
test/fake-ws-set-protocol.js
test/wampy-serializer-handshake-test.js

- Fix wrong Gruntfile extension in package.json scripts;
- Fix fixable ESLint errors by running command "npm run lint:fix";
When running "npm run lint", the following error message appears:
```
Oops! Something went wrong! :(
ESLint: 8.28.0
No files matching the pattern "Gruntfile.js" were found.
Please check for typing mistakes in the pattern.
```
Now, when running "npm run lint" the linter is successfully run.

Fix "npm run lint" not working due to wrong Gruntfile extension

---

src/wampy.js

Now that native Object.assign() is supported by most major browsers, we don't need an internal function to merge objects anymore

Replace internal "_merge" method with Object.assign()

---

src/wampy.js

- Join all conditions into a single expression with descriptive comments to the side of each check;
- Remove _isObject since the following expression: "Object.prototype.toString.call(input) === '[object Object]'" Already checks against primitives, null, DOM, Arrays and built-ins such as Math...

Refactor _isPlainObject

---

src/wampy.js

- Internal _isArray function had a useless Boolean conversion (!!obj) that was always true because all Arrays (even an empty one) evaluate to Truthy.

Use Array.isArray() instead of internal "_isArray" function

---

src/wampy.js

- Before, each message handler had its own session validation block. 
- Now, session validation is done inside function '_wsOnMessage' right before calling the specific handler, thus removing duplicate code.

Move session validation code to '_wsOnMessage'

---

src/wampy.js

The \w regex metacharacter has full browser and Node support and already matches characters included in a-z, A-Z, 0-9, and _ (underscore).
Also, this change joins `_validateURI` "false" exit statements into one statement

Replace [a-zA-Z0-9_] with \w

---

Migrating.md
README.md
src/wampy.js
test/wampy-common-test.js
test/wampy-serializer-handshake-test.js

Fixes #215.
To conform to the [Single Responsibility Principle](https://en.wikipedia.org/wiki/Single-responsibility_principle), `.options()` has now been marked as deprecated and two new methods have been added: `.getOptions()` and `.setOptions()`.

Add .getOptions() and .setOptions()

---

src/wampy.js

This code is never reached since function `connect()` already checks for `this._ws` before safely calling `_initWsCallbacks()`;
Also, in case there was no `this._ws` I'd prefer a runtime error over silently failing and returning with no error message

Remove unused this._ws check from _initWsCallbacks

---

src/utils.js
src/wampy.js
test/wampy-utils-test.js

- Refactor `utils.getWebSocket` so it's easier to unit test;
- Move logic from `utils.getWebSocket` that checked for the browser's Window Object into a new function `utils.getWebSocketFromWindowObject`;
- Add jsdoc comments to functions `utils.getWebSocket` and `utils.getWebSocketFromWindowObject`;

Refactor utils.getWebSocket to improve test coverage by +0.2%

---

test/wampy-utils-test.js

After #249, tests needed to be rewritten a bit for full 100% utils.js branch coverage.
Particularly the `if (!parsedUrl)` check is no longer being tested, since the `if (!ws && isActualNode)` condition is now executed before it.
Now, tests cover all branches and statements and also a few more edge cases, just to be sure.

Adapt wampy-utils-test.js to the getWebSocket refactor

---

src/wampy.js
test/wampy-common-test.js

This avoids keys such as "topic-undefined" when no subscription options are passed

Remove "-undefined" suffix when no options are provided for subscription

---

.github/workflows/build-and-test.yml

Seems that smth changed in coveralls service and now matrix tests are failing...
This its a fix try

configure coveralls action to be parallel-aware

---

src/wampy.js

Trying to fix unhandled promises during disconnection. Updated `_reject_ongoing_promises()` with `Promise.allSettled()` so all promises should be done (fulfilled or rejected).
This might fix #276

Update _reject_ongoing_promises with Promise.allSettled()

---

README.md
src/wampy.js
test/wampy-common-test.js

This PR adds support for Event Retention feature during `publish` and `subscribe` API calls.
This closes #347

Event retention

---

README.md

The docs are not consistent when using variable names for the Wampy instance, alternating between using `wampy` and `ws`
This makes the wampy instance be always called `wampy` in the docs, fixing #456

docs: fix #456
